### ISSUE TITLE
Missing PSF for the provided example data

### ISSUE THREAD

**Issue by gatagat** [CSBDeep/CSBDeep#10]
First of all, thanks for releasing this code including the jupyter notebooks.

I tried to run the isotropic recontruction example with the provided retina data. But since the PSF that was used with this data is not provided, it is not possible to reproduce your results. Please consider adding the PSF. Thanks.

**Comment by uschmidt83** [comment]
You are right, we should add the PSF for this example. We will eventually get to it, but I can't promise when this will happen. If you need it urgently, please send me an email.

Also, please note that the [provided notebooks](http://csbdeep.bioimagecomputing.com/examples/isotropic_reconstruction/) serve as an illustrative example and (while similar) will not directly reproduce the results in the paper.

**Comment by XarlesSta** [comment]
Hi uwe, I have a similar question. As the code is right now the PSF is a dummy matrix of 2-dimensions. Anyhow, the experimental PSF that I have is actually a 3D stack of 8- or 16- bit deep. So my questions are:
1. Should I use a maximal projection XZ as a PSF. That way I would have a 2D matrix, or should I use a 3D matrix ?
2. what is the deep matrix I should use 8 bit or 16 bit. Any advice on what is the best way to convert the image-stack to a matrix for this code. I am asking not out of laziness of how to do that but rather to make sure the PSF has the right properties.

**Comment by Faabgg** [comment]
I am wondering the same thing as the message above. Should I use the 3D stack as PSF?

**Comment by maweigert** [comment]
Hi, 

> I am wondering the same thing as the message above. Should I use the 3D stack as PSF?

The psf to be provided is a 2D array that captures the residual axial (YZ) part of the overall PSF (i.e. how a lateral 2D slice needs to be blurred such to approximate the resolution of an axial slice).
As a first approximation, I would use the central YZ slice of a centered 3D PSF (rotated such that the last dimension of the array is the optical axis).

Hope that helps, 

Martin

**Comment by jboulanger91** [comment]
Hi all, 

Has anyone seen improvements using a true psf for isotropic restoration? 
I have obtained great results with `psf  = np.ones((3,3))/9` however, for a classical 2P microscope the PSF should be around 3um in xz and 0.7 um in xy (NA=1.0, l=1020nm and n=1.33 for zebrafish live imaging).  

How would you input these parameters to define the psf in this notebook? 
It's quite unclear how this shoud be the input to a 3x3 matrix being the 'central YZ slice of a centered 3D PSF'

Thanks a lot for your help, 
Jon

**Comment by nkjerry** [comment]
I'm experiencing similar problems to other users and I'm looking for some guidance on how to create a psf for the isotropicCare training. Has anyone come across any relevant information?

**Comment by maweigert** [comment]
Hi, I finally found time to discuss the choice of the anisotropic part of the PSF, used in the data generation notebook of the isotropic restoration workflow.

Find it in the dev branch: 


https://github.com/CSBDeep/CSBDeep/blob/dev/examples/isotropic_reconstruction/1_datagen.ipynb

**Comment by Luchixiang** [comment]
Hi. I'm still confused about the standard deviation when using the Gaussian approximation for PSF. Does the Std mean the Std value of the central YZ view of my 3D PSF stack? For an 3D stack, the std along an axis (for example, axis=0) should be a 2D image. How to change that to a specific value?
