### ISSUE TITLE
CARE on Win 7 Professional 

### ISSUE THREAD

**Issue by aligheisari** [CSBDeep/CSBDeep#11]
I am trying to install the toolbox on Windows 7. So far, I have updated/installed the requirement as below:
- Python 3.6.6
- pip 18.0
- vitualenv 16.0.0
- wheel 0.32.0
- tensorflow 1.11.0
Now, there is an error with Docker. Since, I am trying to install it on Win 7, I have tried the Docker Toolbox. However, I get the this error saying: "Looks like something went wrong in step 'Looking for vboxmanage.exe' ..."

Beside moving toward Linux platform, Would be there any solution?

Thanks

**Comment by fjug** [comment]
@uschmidt83 After installing CARE on the wonderful Aquifer machines under Windows... would you happen to know how to help @aligheisari?

**Comment by uschmidt83** [comment]
Hi @aligheisari, I haven't used Docker myself and don't know how to solve your problem (maybe @tboo can).

However, I've successfully used CARE with a standard [Anadona Python](https://www.anaconda.com/download/#windows) installation on Windows.

**Comment by imagejan** [comment]
I'd suggest adding an `enviroment.yml` to this repository, so that installation with conda gets as easy as:

    conda env create -f enviroment.yml

It could look similar to this:

```
# Python environment with GPU for use with CSBDeep
# install: conda env create -f environment.yml
# update:  conda env update -f environment.yml
name: csbdeep
dependencies:
  - wheel
  - tensorflow-gpu
```

**Comment by tboo** [comment]
Hi @aligheisari,

to run CARE with in a docker container you actually need the NVIDIA docker runtime (nvidia-docker), which only runs on Linux. 

But running CARE outside a docker container should be no problem on Windows. The installation is just a little bit more time consuming as you have to manually install Python, CUDA, cuDNN and Tensorflow and CARE of course.

**Comment by aligheisari** [comment]
Hi @fjug, @uschmidt83, @imagejan and @tboo,

Thank you very much for your responses. I will try to run CARE outside docker and manually installing the requirement. However, I should mention that I am installing tensorflow for CPU-only. Accordingly, installing CUDA and cuDNN should not be required, am I right?

**Comment by aligheisari** [comment]
Totally agree with you. Unfortunately that´s what I have for now.
Soon we´ll be changed ;)

**Comment by tboo** [comment]
Consider trying our docker image on the AWS p3.2xlarge instances. 3$/hr may be well invested ;)

**Comment by maweigert** [comment]
Closing due to non-activity (please reopen if still relevant)
