### ISSUE TITLE
Multi GPU Support

### ISSUE THREAD

**Issue by a-jacobo** [CSBDeep/CSBDeep#12]
CSBDeep is great! I was wondering if you plan to support multi-gpu training and reconstruction at some point in the future.

**Comment by uschmidt83** [comment]
I'm glad that you like it.

I've personally never looked into multi-GPU training/prediction and thus don't know how much work it would require. (pinging @psteinb)

**Comment by a-jacobo** [comment]
According to this website, as of Keras 2.0.9 it only takes a few extra lines of code to build a multi-gpu model: 

https://www.pyimagesearch.com/2017/10/30/how-to-multi-gpu-training-with-keras-python-and-deep-learning/

Let me know if you are interested in implementing it! I would be happy to test it.

**Comment by psteinb** [comment]
on the tensorflow backend, the multi-gpu training with keras is straight forward, see this [class](https://keras.io/utils/#multi_gpu_model) for more details.

**Comment by maweigert** [comment]
Closing due to non-activity (please reopen if still relevant)
