### ISSUE TITLE
axes_check_and_normalize(axes,img.ndim) throws an error during the prediction

### ISSUE THREAD

**Issue by Pepperify** [CSBDeep/CSBDeep#14]
Hello,

I have a  problem with using my model after I have succesfully created it in Collaboratory. I wonder if the problem is in my lines or in the fact that I am using the latest version of Tensor flow in the collaboratory?

So, after the model has finnished I have this code:

First, I load a stack of 20 images in to 'X':

X= io.imread('drive/csbdeep_data/predict/5_stack.tif')

model = CARE(config=None, name='peter1', basedir='models')
print (X.shape)
print(X.ndim)
print (axes)

And the I get this OUTPUT:

Loading network weights from 'weights_best.h5'.

(20, 658, 658) #shape of X
3 #dimension of X
STYXC #axes 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-2c520c0074ef> in <module>()
     16 
     17 
---> 18 restored=model.predict('X', axes='YXC', n_tiles=None)
     19 

/usr/local/lib/python3.6/dist-packages/csbdeep/models/care_standard.py in predict(self, img, axes, normalizer, resizer, n_tiles)
    323 
    324         """
--> 325         return self._predict_mean_and_scale(img, axes, normalizer, resizer, n_tiles)[0]
    326 
    327 

/usr/local/lib/python3.6/dist-packages/csbdeep/models/care_standard.py in _predict_mean_and_scale(self, img, axes, normalizer, resizer, n_tiles)
    360         """
    361         normalizer, resizer = self._check_normalizer_resizer(normalizer, resizer)
--> 362         axes = axes_check_and_normalize(axes,img.ndim)
    363         _permute_axes = self._make_permute_axes(axes, self.config.axes)
    364         def _permute_n_tiles(n,undo=False):

AttributeError: 'str' object has no attribute 'ndim'estored=model.predict('X', axes='YXC', n_tiles=None)
`

Thanks for any help, Peter

**Comment by uschmidt83** [comment]
Hi Peter, it seems that it should be `X` instead of `'X'` and `'TYX'` instead of `'YXC'` in `model.predict`, i.e.
`model.predict(X, axes='TYX', n_tiles=None)`.

Uwe

**Comment by Pepperify** [comment]
Thank you Uwe, now it is working the way it should. I got my first dataset processed, and it is looking very good indeed! Thank you for providing this tool.

Peter
