### ISSUE TITLE
Concatenating training patches from multiple .npz files

### ISSUE THREAD

**Issue by elktoe** [CSBDeep/CSBDeep#17]
Experiments have different PSFs becasue of zoom factor on the microscope. So when creating semi-synthetic training data patchs I have multiple .npz files (one for each psf).

Can all the patches be concatenated into one .npz so all patches can be read into load_training_data? 
Alternativley can load_training_data accept multiple .npz files? 
Cheers,

**Comment by uschmidt83** [comment]
First of all, maybe it's better to train a separate model if the PSF changes substantially.  
If you still want to use data from several `.npz` files, I suggest to load the training data like this:

```python
# assumes that all .npz files contain data of the same size with the same axes
npz_files = ['data/my_training_data_1.npz', 'data/my_training_data_2.npz']
n = len(npz_files)
X, Y, X_val, Y_val = [None]*n, [None]*n, [None]*n, [None]*n
for i,fname in enumerate(npz_files):
    (X[i],Y[i]), (X_val[i],Y_val[i]), axes  = load_training_data(fname, validation_split=0.1)

X = np.concatenate(X,axis=0)
Y = np.concatenate(Y,axis=0)
X_val = np.concatenate(X_val,axis=0)
Y_val = np.concatenate(Y_val,axis=0)

c = axes_dict(axes)['C']
n_channel_in, n_channel_out = X.shape[c], Y.shape[c]
```
Best,
Uwe

**Comment by maweigert** [comment]
Closing due to non-activity (please reopen if still relevant)
