### ISSUE TITLE
session graph name needed as input to initialize tensorboard?

### ISSUE THREAD

**Issue by elktoe** [CSBDeep/CSBDeep#18]
Hi!
Starting TensorBoard with  `tensorboard --logdir= /path`  gives the below error:
> No dashboards are active for the current data set. 
> Probable causes: 
> - You haven’t written any data to your event files. 
> - TensorBoard can’t find your event files.

I wanted to add
```
writer = tf.summary.FileWriter("/models/my_model")
writer.add_graph(sess.graph)
```
but I don't know the name of the graph. How do I get TensorBoard to visualize the the graph created by CARE. I am specifically using IsotropicCare. 
Thanks!

**Comment by uschmidt83** [comment]
I guess you see the "error" in the browser, not the command line, right? The message indicates that no TensorBoard event files have been found. Is `/path` pointing to the correct folder? You haven't disabled TensorBoard in the `Config`? The training has already finished at least one epoch?

Why do you want to visualize the TensorFlow [graph](https://www.tensorflow.org/guide/graph_viz)? (We do not save the graph for display in TensorBoard, but you could change this.)

Uwe

**Comment by uschmidt83** [comment]
> Starting TensorBoard with `tensorboard --logdir= /path` gives the below error:

I recently came across this problem myself. It's apparently important to not have a space after `=`, i.e. start TensorBoard like this: `tensorboard --logdir=/path`.

Hope this helps,
Uwe
