### ISSUE TITLE
3D Deconvolution

### ISSUE THREAD

**Issue by Zengzhen9982** [CSBDeep/CSBDeep#19]
Hi,
I'm wondering if there is a demo of 3D deconvolution for 3D grayscale time series.
Before I have tried the Deconvolution (Microtubules) with 2D time series from the z-stack time series (one of the Z-stack) separately ,then combined them together for 3D reconstruction.
Do you know any better solution?
Thank you in advance!

**Comment by Zengzhen9982** [comment]
@fjug @royerloic

**Comment by fjug** [comment]
Are you interested in CARE denoising or do you also want to go down the road to isotropic resolution (e.g. address undersampled Z)?

**Comment by Zengzhen9982** [comment]
Thank you for your reply.I believe both are important for observing the fluorescent labeled endoplasmic reticulum and the following 3D reconstruction.

**Comment by fjug** [comment]
Ok, I'm really not sure what to say. I try to answer your original question:
None of the existing CARE setups is designed to leverage time series data. BUT obviously CARE is very much intended to work on a series of frames and hence help you to analyze your time series.

If this is not clear, I will try to say the same thing another time using different words. CARE, once trained on data of (usually multiple) single time-point images or image volumes, is very much intended to be applied to all frames (time points) you acquired in a time series. These applications are, though, performed sequentially and independently. CARE, so far, does not combine the information of adjacent time-points to improve predictions or such.

And yes, the examples we offer in the CSBDeep python packages contain 3D denoising (http://csbdeep.bioimagecomputing.com/doc/models.html#csbdeep-models-care), upsampling (http://csbdeep.bioimagecomputing.com/doc/models.html#csbdeep-models-upsamplingcare), and networks that improve z-resolution (http://csbdeep.bioimagecomputing.com/doc/models.html#csbdeep-models-isotropiccare). The last-mentioned task naturally requires that XY-slices contain all the visual features you would also see in XZ- and YZ-slices. If this is not the case I'd not be expecting very good results here.

Last but not least, please let me point out that for all CARE training sessions you should be careful to have perfectly aligned training data pairs. Easiest is to acquire training data already such that you have a pixel-perfect alignment of you training data pairs. If this is not possible (e.g. for SEM pairs or so) you will need to register your data prior to training and that will open yet another can of worms...

Hope this helps,
Florian

**Comment by Zengzhen9982** [comment]
Hi Florian,


Thank you for your answer! I will run a test and I will let you know .


Best,


Zengzhen

________________________________
发件人: Florian Jug <notifications@github.com>
发送时间: 2019年2月13日 18:14
收件人: CSBDeep/CSBDeep
抄送: Zengzhen LIU; Author
主题: Re: [CSBDeep/CSBDeep] 3D Deconvolution (#19)


Ok, I'm really not sure what to say. I try to answer your original question:
None of the existing CARE setups is designed to leverage time series data. BUT obviously CARE is very much intended to work on a series of frames and hence help you to analyze your time series.

If this is not clear, I will try to say the same thing another time using different words. CARE, once trained on data of (usually multiple) single time-point images or image volumes, is very much intended to be applied to all frames (time points) you acquired in a time series. These applications are, though, performed sequentially and independently. CARE, so far, does not combine the information of adjacent time-points to improve predictions or such.

And yes, the examples we offer in the CSBDeep python packages contain 3D denoising (http://csbdeep.bioimagecomputing.com/doc/models.html#csbdeep-models-care), upsampling (http://csbdeep.bioimagecomputing.com/doc/models.html#csbdeep-models-upsamplingcare), and networks that improve z-resolution (http://csbdeep.bioimagecomputing.com/doc/models.html#csbdeep-models-isotropiccare). The last-mentioned task naturally requires that XY-slices contain all the visual features you would also see in XZ- and YZ-slices. If this is not the case I'd not be expecting very good results here.

Last but not least, please let me point out that for all CARE training sessions you should be careful to have perfectly aligned training data pairs. Easiest is to acquire training data already such that you have a pixel-perfect alignment of you training data pairs. If this is not possible (e.g. for SEM pairs or so) you will need to register your data prior to training and that will open yet another can of worms...

Hope this helps,
Florian

―

**Comment by maweigert** [comment]
Closing due to non-activity (please reopen if still relevant)
