### ISSUE TITLE
Sample Patches Coordinates

### ISSUE THREAD

**Issue by KaterynaCavorit** [CSBDeep/CSBDeep#20]
Hi,

I would like to use care to train two classes. I would like to make a projection from 3D to two 2D images. I'm trying to find if it is possible to get coordinates of the patch from X during sampling the patches with 

`create_patches_reduced_target()`

I want to sample the same patches from the other target class.
It seems that 

`image_pairs = compose(*tf.generator)(raw_data.generator())`

samples this patches, but is possible to get somehow the coordinates of the patch?

Cheers 
Kateryna
Student at Kainmüller Lab

**Comment by KaterynaCavorit** [comment]
Or will it work, if I stack the Y1 and Y2 into Y before generating patches? Or does care expect Y always 1D on Z-Axis?

**Comment by uschmidt83** [comment]
Hi Kateryna,

> I'm trying to find if it is possible to get coordinates of the patch from X during sampling

this would require some (serious) modification of the code.

As an alternative, you may set the same random seed (e.g. `np.random.seed(42)`) before you call `create_patches_reduced_target(..., patch_filter = None)`. This should always give you the same coordinates (and normalization) for the extracted patches. Note that I set `patch_filter = None`, which means that the patch location will not depend on the content of Y. ([Explanation](http://csbdeep.bioimagecomputing.com/doc/datagen.html?highlight=patch_filter#csbdeep.data.create_patches) of `patch_filter`.)

Hope that helps,
Uwe

**Comment by KaterynaCavorit** [comment]
Wow, that is a really cool workaround! I will try it. Thanks

**Comment by KaterynaCavorit** [comment]
I've tried to save the target image as 3D where the size of the z-Axis is 2. 
e.g.
```
y1 = imread('data/gt_test/155325_20161012_EcadGFP_79rAEL_f0000-projection0.tif')
y2 = imread('data/gt_test/155325_20161012_EcadGFP_79rAEL_f0000-projection1.tif')
y = np.stack((y1,y2))
imsave('gt_pic2D/155325_20161012_EcadGFP_79rAEL_f0000.tif', y, compress=6, metadata={'axes': 'ZYX'})

raw_data = RawData.from_folder (
    basepath    = 'data/',
    source_dirs = ['source_pic'],
    target_dir  = 'gt_pic2D',
    axes        = 'ZYX',
)

Is there a possibility to use the `create_patches_reduced_target(....)` with Z in size of 2?

Thanks

**Comment by uschmidt83** [comment]
> Is there a possibility to use the `create_patches_reduced_target(....)` with Z in size of 2?

Currently not. It's also not an easy change, due to the current assumptions in the code.

**Comment by KaterynaCavorit** [comment]
Thanks a lot
