### ISSUE TITLE
Tifffile

### ISSUE THREAD

**Issue by KaterynaCavorit** [CSBDeep/CSBDeep#22]
I got data with compression 'LZW' instead of 'lzw' and the module tifffile cannot handle this. I had to modify rawdata.py in csbdeep to load imread from skimage.io instead from tifffile.

Is there a particular reason why you using tifffile package for opening tiffiles instead of just skimage.io.

**Comment by uschmidt83** [comment]
I personally never had a problem with `tifffile`, but I also don't use compression. Also, last thing I knew is that `skimage.io` was simply using `tifffile` under the hood. I guess that's not true anymore?

**Comment by uschmidt83** [comment]
Btw, you can also use numpy arrays directly with [`RawData.from_arrays`](http://csbdeep.bioimagecomputing.com/doc/datagen.html#csbdeep.data.RawData.from_arrays).

**Comment by KaterynaCavorit** [comment]
> Btw, you can also use numpy arrays directly with [`RawData.from_arrays`](http://csbdeep.bioimagecomputing.com/doc/datagen.html#csbdeep.data.RawData.from_arrays).

Yeah, I was already trying that too. Now I have to merge all ideas to predict 2 classes :)

**Comment by cgohlke** [comment]
>  I got data with compression 'LZW' instead of 'lzw' and the module tifffile cannot handle this

Newer versions of `tifffile` are using the optional [`imagecodecs`](https://pypi.org/project/imagecodecs/) package to decode LZW, JPEG, J2K, etc. compressed images. The older `tifffile` module in scikit-image bundles an LZW decoder.

**Comment by maweigert** [comment]
Hi @KaterynaCavorit,

Yes, I noticed that too. `tiffffile` won't open lzw encoded tiff files anymore (e.g. some that were exported via Fiji). E.g. trying to open the following stack 

https://github.com/CSBDeep/CSBDeep/files/2890929/lzw_compressed.tif.zip

throws an error for me with a fresh install of`tiffffile` (on OSX 10.12).

You have at least 2 options:

1) downgrade `tifffile`, e.g. via 
`pip install tifffile==0.15.1`

2) use `skimage.io.imread` 

@cgohlke Thanks for the explanation! Sadly, installing `imagecodecs` seems to be not really easy on OSX (I didn't manage). Is there any other workaround for Mac users? I'm using `tifffile` all the time (without having to require `scikit-image`) and it would be great to use the latest version (Currently I can't upgrade for the broken lzw reason).

**Comment by cgohlke** [comment]
> installing `imagecodecs` seems to be not really easy on OSX

I'm aware of that. I'll consider a separate "`imagecodecs_lite`" package, a limited subset of `imagecodecs` with just straight C/Cython code and no external C library dependencies, which should cover LZW, PackBits, Delta, Bitorder, and Floating Point predictors.

**Comment by KaterynaCavorit** [comment]
@maweigert  When I loaded and exported one tiff file via Fiji, the `tifffile` module works fine.  
and yes, I'm using the `scimage.io.imread`.

Cheers

**Comment by cgohlke** [comment]
@maweigert, could you please try to `pip install imagecodecs-lite` on OSX and report how/if it worked? The next version of `tifffile` will use [`imagecodecs-lite`](https://pypi.org/project/imagecodecs-lite/) as a fallback if the [`imagecodecs`](https://pypi.org/project/imagecodecs/) package is not installed.

**Comment by maweigert** [comment]
@cgohlke Installing `imagecodecs-lite` works fine, but how should I proceed from there? If I try to use 
`imagecodecs_lite.lzw_decode` on the raw bytestring of the file given above I get `IcdError: icd_lzw_size returned ICD_LZW_INVALID`. Any ideas?

**Comment by cgohlke** [comment]
Thanks for testing!

> but how should I proceed from there?

Wait for the next version of `tifffile >= 2019.2.22` to be released (hopefully today).

`imagecodecs_lite.lzw_decode` is a decoder for LZW compressed strips or tiles found in TIFF files, not a decoder for whole TIFF files.

**Comment by maweigert** [comment]
> Use [`tifffile >= 2019.2.22`](https://pypi.org/project/tifffile/).

Wow, it works now!! :)) 
Thanks for the super fast response and fix!
