### ISSUE TITLE
Minimum number of examples to train a CARE model

### ISSUE THREAD

**Issue by YotamLif** [CSBDeep/CSBDeep#23]
Hi,

First of all thanks a lot for the great CSBDeep framework. I've found very useful for my project.

I was wondering what is the minimum number (according to what you've experienced) to egt a well trained CARE model.

In this example: 
https://nbviewer.jupyter.org/url/csbdeep.bioimagecomputing.com/examples/denoising3D/1_datagen.ipynb
you say that you have to get about 10-50 stacks of good and bad SNR examples.

But in the supplementary information to the "Content-Aware Image Restoration: Pushing the Limits of
Fluorescence Microscopy" article there's a table in page 31 which says the number of examples you used for your research was about 17,000 which is about 3 orders of magnitude more than the above number.

Of course the more examples the better for training a model but what is the number for the major quality increase?

Thanks a lot,
Yotam

**Comment by uschmidt83** [comment]
Hi Yotam,

> First of all thanks a lot for the great CSBDeep framework. I've found very useful for my project.

We're always glad to hear it!

> [...] you say that you have to get about 10-50 stacks of good and bad SNR examples.
> But in the supplementary information [...] says the number of examples [...] was about 17,000 [...]

The 10-50 refers to the number of large 3D image stacks from the microscope, whereas the 17000 refers to the number of (much smaller) training patches *extracted* from those large 3D stacks, as [indicated](https://nbviewer.jupyter.org/url/csbdeep.bioimagecomputing.com/examples/denoising3D/1_datagen.ipynb#Generate-training-data-for-CARE) by the `n_patches_per_image` parameter used in the `create_patches()` function.

For example, if you had 50 image stacks and wanted to generate 17000 patches for training, you'd set `n_patches_per_image = 340`.

Best,
Uwe
