### ISSUE TITLE
Image view in Tensorboard during training

### ISSUE THREAD

**Issue by tboo** [CSBDeep/CSBDeep#24]
It looks like that the image view of the training progress in tensorboard (v1.7) does not respond to which models/runs are selected for display. The results of all models trained in this session are always displayed. Works fine for the scalars though.
And a feature request for the image view in tensorboard: Would be great to have the ground truth displayed there as well.

**Comment by tboo** [comment]
Sorry, that seems to be a browser issue. After a browser page-refresh the panels are properly updated. Feature request remains :)

**Comment by uschmidt83** [comment]
Tensorboard is always a bit flaky...

The requested feature (ground truth in image tab) is now implemented in the dev branch.
Until a new release, you can install it like this:
```
pip uninstall -y csbdeep
pip install git+https://github.com/CSBDeep/CSBDeep.git@dev
```

**Comment by tboo** [comment]
Great. Thanks.
