### ISSUE TITLE
Segmentation Pipeline

### ISSUE THREAD

**Issue by tristan-mcrae-rochester** [CSBDeep/CSBDeep#29]
The paper says you applied "a simple nuclei segmentation
pipeline" to your images. Could the code for that be shared here?

**Comment by colemanbroad** [comment]
Hi Tristan,

The segmentation used on both drosophila and tribolium datasets was simple thresholding + connected components. For labeling connected components we used the `label` function from `scipy.ndimage`. Here is a simple example for a single threshold value:

```python
import numpy as np
from scipy.ndimage import label
from scipy.ndimage import convolve
import matplotlib.pyplot as plt

## generate fake data: randomly placed blobs in 3D
coords = (np.random.rand(100,3) * [50,100,200]).astype(int)
img = np.zeros((50,100,200))
img[list(coords.T)] = 1
img = convolve(img, np.ones((3,3,3)))
img = convolve(img, np.ones((3,3,3)))
img = convolve(img, np.ones((3,3,3)))

## perform the segmentation for single threshold value
assert img.ndim in [2,3]
threshold = np.percentile(img,98)
segmentation = label(img > threshold)[0]

## plot the resulting segmentation in 2D
plt.imshow(segmentation.max(0))
plt.show()
```

For drosophila we also preprocess images passing them through a random forest pixelwise classifier from [ilastik](https://www.ilastik.org/) trained to enhance the nucleus signal.

Of course I'd like to make the full code available (which includes running over a range of thresholds, computing scores vs ground truth, and making figures). But, as I have to hand in a thesis this fall, it's unlikely that I'll get to that before the end of the year. 

I hope this example will do for now?

**Comment by tristan-mcrae-rochester** [comment]
Yes thank you, this is exactly what I was looking for.
