### ISSUE TITLE
TF to Keras model

### ISSUE THREAD

**Issue by sebherbert** [CSBDeep/CSBDeep#32]
Hi,

I would like to recreate a Keras model from a TF model (so the opposite operation of the export() function). Do you know if there is a way to do this? 

I've tried to create unet architecture (based on this [code](https://github.com/zhixuhao/unet)) and load the weights from the TF model, but I didn't manage to recreate the right architecture to do so. 

Thanks! 

Sebastien

**Comment by tboo** [comment]
Hi Sebastien - 

this is something to ask the Keras team and it has been adressed [here](https://github.com/keras-team/keras/issues/8026)

Good luck :)
