### ISSUE TITLE
tqdm notebook cleanup for model training output

### ISSUE THREAD

**Issue by padster** [CSBDeep/CSBDeep#33]
I've started running CSBDeep in a jupyter notebook for isotropic restoration to great success (thanks!) but the output on the model fitting stage is fairly verbose, and grows linearly with the number of epochs.

There are some techniques for getting keras to output progress to a tqdm notebook UI (https://github.com/bstriner/keras-tqdm), I was wondering if this had been tried, or alternatively if it'd be fine for me to add?

**Comment by uschmidt83** [comment]
> I've started running CSBDeep in a jupyter notebook for isotropic restoration to great success (thanks!)

Glad to hear it!

> the output on the model fitting stage is fairly verbose, and grows linearly with the number of epochs.

That is true, but I personally don't consider it to be a big problem.
Large outputs can (or will even automatically?) be collapsed and scrolled through.

To be honest, I monitor model training always in TensorBoard and don't pay attention to the notebook while training.

> (https://github.com/bstriner/keras-tqdm), I was wondering if this had been tried

I'm aware of this, but don't consider it to be a major improvement.
Also, it has the downside that the output is not preserved when the notebook is just viewed online.

Sorry for the late reply.

Best,
Uwe
