### ISSUE TITLE
Access to changed subsample value

### ISSUE THREAD

**Issue by padster** [CSBDeep/CSBDeep#35]
Is there any way to provide access to the altered subsample value here?
https://github.com/CSBDeep/CSBDeep/blob/2c374d5641f1eba8aafbb8d2b858814bc281701a/csbdeep/data/transform.py#L284

I currently have a collection of (x, y, z) points in the source image, and I'd like to map those to locations in an isotropic-CARE restored volume, however the scale factor is changing slightly between what I give, and what ends up being used.

I'm not sure the best way to expose this, but perhaps adding a public method that exposes an API to _adjust_subsample; my images are all the same shape, so something like: `adjust_anisotropic_subsample(target_subsample, target_shape, crop_threshold)`
Then I could call that once at the start with my image shape, save the result, and give that example both to my anisotropic_subsample (which stays the same, but now doesn't warn as I give it a good value), as well as use this to scale my (x, y, z) positions to the correct location.

Note that this is low priority, as the difference between used (4.89) and desired (4.88599) is small, so unlikely to cause errors, but an exact match would feel cleaner.

**Comment by uschmidt83** [comment]
> Note that this is low priority, as the difference between used (4.89) and desired (4.88599) is small, so unlikely to cause errors, but an exact match would feel cleaner.

I understand the issue, but indeed consider it very low priority.
Also, I don't think it will matter in practice.

A more important issue, and one we haven't gotten to, is the choice of PSF for isotropic reconstruction (see [discussion here](https://forum.image.sc/t/isotropic-care-psf-questions/28514)).

Sorry for the late reply.

Best,
Uwe
