### ISSUE TITLE
AttributeError with limit_gpu_memory

### ISSUE THREAD

**Issue by flevet** [CSBDeep/CSBDeep#40]
Hi,

I just installed CSBDeep and I would be interested in using the limit_gpu_memory. When uncommented in the jupyter notebook, I have this error :

```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-4d7e1208218d> in <module>
----> 1 limit_gpu_memory(fraction=0.5)

~\Anaconda3\envs\tf\lib\site-packages\csbdeep\utils\tf.py in limit_gpu_memory(fraction, allow_growth)
     43     fraction is None or (np.isscalar(fraction) and 0<=fraction<=1) or _raise(ValueError('fraction must be between 0 and 1.'))
     44 
---> 45     if K.tensorflow_backend._SESSION is None:
     46         config = tf.ConfigProto()
     47         if fraction is not None:

AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_SESSION'
```
Is it a problem related to versions of tensorflow-gpu, cuda and cuDNN ?

For information I'm using Anaconda with Python 3.7 and I created a specific environement:

```
conda create -n tf
conda activate tf
conda install tensorflow=1.14.0
conda install tensorflow-gpu=1.14.0
pip install csbdeep
```

Best,
Florian

**Comment by maweigert** [comment]
Hi Florian, 

This looks a `keras` vs `tensorflow` version mismatch. Can you try to reinstall `keras` ?

```
pip uninstall keras
pip install -U keras
```

**Comment by flevet** [comment]
Hi Martin,

No change unfortunately. For information, it is keras-2.3.1 that is being installed.

**Comment by maweigert** [comment]
Hi Florian, 

You are right, it does fail for keras > 2.2.5 (the _SESSION attribute [was removed at some point](https://github.com/keras-team/keras/commit/bbba9cede7cf9603598a78b6b27d87599dff8312)). 
We will look into that, thanks for pointing this out! 

In the meantime, after downgrading keras it should work again 

 ```
pip uninstall keras csbdeep
pip install keras==2.2.5 csbdeep
```

**Comment by flevet** [comment]
Hi Martin,

Thanks, it resolved the problem !
