### ISSUE TITLE
Remove h5py<3.0 requirement

### ISSUE THREAD

**Issue by ElpadoCan** [CSBDeep/CSBDeep#59]
Since the bug is probably solved (see [here](https://github.com/tensorflow/tensorflow/issues/44467#issuecomment-1006167173)), is it possible to remove the requirement `h5py<3; python_version<'3.9'`? I am having troubles with pip backtracking if I put both tensorflow >2.4 and CSBDeep as requirements of my project. Thanks!

**Comment by uschmidt83** [comment]
Discussion at https://github.com/stardist/stardist/issues/180
