### ISSUE TITLE
Model initialization and training taking too much time

### ISSUE THREAD

**Issue by sim-anna** [CSBDeep/CSBDeep#63]
Hi,

I'm trying to run the 3D denoising model (CARE 3D).

However, the model initialization command:

```model = CARE(config, 'my_model', basedir='models')``` takes upto 5 minutes to initialize the model.

Once this is finished and I try to train via:

```history = model.train(X,Y, validation_data=(X_val,Y_val))```

This basically stalls at epoch 1 and does not go further. No TensorBoard logs are created. Image is below.

![image](https://user-images.githubusercontent.com/110496566/197427436-300f9944-3b20-4f70-9704-f44afbb1a595.png)

I have 24 Gb of GPU memory available so this should not be an issue.

Can you please advise?

Edit: On further debugging, I'm getting this error:

![image](https://user-images.githubusercontent.com/110496566/197428545-73e874f7-65a0-45d0-b55b-2d6d865ed897.png)

I'm on Python 3.8 and Tensorflow 2.4, and cuda 10.1.

**Comment by uschmidt83** [comment]
Hi @sim-anna, this looks like an installation issue and seems unrelated to CSBDeep. Sorry, but I can't really help you here.
Sorry for the late reply and good luck.

**Comment by sim-anna** [comment]
I solved it upgrading cudatoolkit.
