### ISSUE TITLE
Python version of imageJ - Demo/3D denoising/model-planaria

### ISSUE THREAD

**Issue by orena1** [CSBDeep/CSBDeep#65]
Hi,
I want to use the ImageJ Demo model for 3D denoising, I saw that it is possible to [train it using sample data](https://github.com/CSBDeep/CSBDeep/blob/master/examples/denoising3D/2_training.ipynb) (Assuming this is the process to get the model used in the ImageJ sample plugging) but is there an option to just download the[ model and use it for prediction ](https://github.com/CSBDeep/CSBDeep/tree/master/examples/denoising3D)?

EDIT:
I've tried to train using the Jupiter notebook example and the results that I get with the trained model is much worse than what I get from the plugin 
![image](https://user-images.githubusercontent.com/8983713/208522410-e9d8ae94-cb14-4c0d-a43e-796f2c690813.png)

Thanks

**Comment by uschmidt83** [comment]
> Hi, I want to use the ImageJ Demo model for 3D denoising, I saw that it is possible to [train it using sample data](https://github.com/CSBDeep/CSBDeep/blob/master/examples/denoising3D/2_training.ipynb) (Assuming this is the process to get the model used in the ImageJ sample plugging)

If I remember correctly, this notebook might not be exactly what we did to train the model, but you can essentially train it like that.

> EDIT: I've tried to train using the Jupiter notebook example and the results that I get with the trained model is much worse than what I get from the plugin

However, we used much more data for training, which you can find here: https://publications.mpi-cbg.de/publications-sites/7207/

> is there an option to just download the[ model and use it for prediction ](https://github.com/CSBDeep/CSBDeep/tree/master/examples/denoising3D)?

I don't remember which Python model specifically we converted to create the ImageJ demo model, but I could dig out the models we used for the results in the paper. Let me know. Also note that we used an ensemble (of 5 models) for the paper, not a single one.

Sorry for the very late reply,
Uwe

**Comment by uschmidt83** [comment]
Sorry for the delay, but you can download a tribolium model [here](https://github.com/CSBDeep/CSBDeep/files/10528596/tribolium.zip). This is one of the 5 ensemble models that we used in the paper. I'm confident – but not 100% sure – that this is the same model as provided in Fiji.

After unzipping, you can load it like any other CARE model, i.e. `model = CARE(None, name='tribolium')`.

Note that this is a model that can produce a "probabilistic" output (cf. [example](https://nbviewer.org/url/csbdeep.bioimagecomputing.com/examples/denoising2D_probabilistic/2_prediction.ipynb)). If you care about probabilistic prediction, please load the model as follows:

```python
class TriboliumCARE(CARE):
    def _build(self):
        return nets.custom_unet(
            input_shape     = self.config.unet_input_shape,
            n_channel_out   = self.config.n_channel_out,
            prob_out        = self.config.probabilistic,
            residual        = self.config.unet_residual,
            n_depth         = self.config.unet_n_depth,
            kernel_size     = (self.config.unet_kern_size,)*self.config.n_dim,
            n_filter_base   = self.config.unet_n_first,
            last_activation = self.config.unet_last_activation,
            eps_scale       = 0.0,
        )

model = TriboliumCARE(None, name='tribolium')
```

Best,
Uwe

**Comment by orena1** [comment]
Thank you very much @uschmidt83  but actually the results of the `tribolium` model are very poor relative to the `planaria` model, it seems that I wrote the name of the model that I need only in the title of the issue and not in content,
Is it possible to also get the weights of the planaria model?

Thanks a lot,
Oren

**Comment by uschmidt83** [comment]
You can download a planaria model [here](https://github.com/CSBDeep/CSBDeep/files/10556429/planaria.zip). Again, this is likely the same model as provided in Fiji.

Use it via `model = CARE(None, name='tribolium')` or `model = LegacyCARE(None, name='planaria')` if you want probabilistic output (as explained above).

Best,
Uwe

**Comment by orena1** [comment]
Thanks a lot, works great!
