### ISSUE TITLE
create_patches does not have support for "channels_last" data format

### ISSUE THREAD

**Issue by evrova** [CSBDeep/CSBDeep#7]
Dear CSBDeep Team,

I work with 2D data and noticed that the current implementation of create_patches() always puts the channels first, so does not support the "channels_last" configuration.

One solution would be to replace (it is in the create_patches function):

    axes = 'SC'+axes.replace('C','')
         if channel is None:
            X = np.expand_dims(X,1)
            Y = np.expand_dims(Y,1)
         else:
            X = np.moveaxis(X, 1+channel, 1)
            Y = np.moveaxis(Y, 1+channel, 1)

with the following:

    #import added
    from ..utils import backend_channels_last

    if backend_channels_last():
        if channel is None:
            X = np.expand_dims(X,-1)
            Y = np.expand_dims(Y,-1)
        else:
            X = np.moveaxis(X, 1+channel, -1)
            Y = np.moveaxis(Y, 1+channel, -1)
        axes = 'S' + axes.replace('C', '') + 'C'
    else:
        if channel is None:
            X = np.expand_dims(X,1)
            Y = np.expand_dims(Y,1)
        else:
            X = np.moveaxis(X, 1+channel, 1)
            Y = np.moveaxis(Y, 1+channel, 1)
        axes = 'SC' + axes.replace('C', '')

Best,
Gabriela

**Comment by uschmidt83** [comment]
Dear Gabriela,

we only store the training data with channels being at the front, all our models actually support (and at the moment even require) the ["channels_last"](https://keras.io/backend/#kerasjson-details) configuration of Keras.
The training data can be loaded with [csbdeep.io.load_training_data](http://csbdeep.bioimagecomputing.com/doc/training.html#csbdeep.io.load_training_data), which will automatically move the channels to the end of the array, as Keras/TensorFlow requires with the "channels_last" configuration.

May I ask why it is important to you to store the channels last?

**Comment by evrova** [comment]
Thank you very much for the quick reply.

Yes everything else worked well. "channels_last" was the default configuration saved in my keras.json file, so there is no specific reason.

I saw that you take care of this in the load_training_data function, but if I want to train a model after creating the patches, without saving them in .npz and reloading them, then this change is necessary.

Also, do you think that a good idea would be to have the option of creating patches in a randomized way on the CPU while training (so the generator would read random images from disk and create random patches on the fly)?

Thank you,
Gabriela

**Comment by uschmidt83** [comment]
> I saw that you take care of this in the load_training_data function, but if I want to train a model after creating the patches, without saving them in .npz and reloading them, then this change is necessary.

Ok, so you want to create the training data and *not* save it, but directly use it for training. In this case, you are right that one needs to manually move things to the right locations, etc. However, I wouldn't consider this a typical use case.

> Also, do you think that a good idea would be to have the option of creating patches in a randomized way on the CPU while training (so the generator would read random images from disk and create random patches on the fly)?

I think *simple* data augmentation on the fly during training is a good idea (e.g. rotations and flips). However, loading entire raw images and extracting patches (essentially what `create_patches` does) will probably be to slow in many cases.

Best,
Uwe

**Comment by tlambert03** [comment]
for what it's worth, I created a generator to do just that (extract patches on on the fly during training) and it was _much_ slower...   after trying to speed it up for a while, I gave up and went back to pre-extraction

**Comment by evrova** [comment]
Thank you!
