### ISSUE TITLE
Memory limits

### ISSUE THREAD

**Issue by CMCI** [CSBDeep/CSBDeep#73]
I'm a core facility manager trying to put together a workflow for people that I work with to be able to use a CARE network without too much programming experience. I have taken care of much of the prep work, but what I would love to be able to do is limit the size of the training data file to the memory limit of the GPU as part of the `rawdata.from_folder` function. I have tried cropping the list of pairs with the following lines of code:
```
if len(pairs) > 80:
    pairs = pairs[0:80]
```
But that seems to cause the `datagen` to hang before actually saving the npz file. 

80 is an appropriate cutoff for our z-stacks, but if they were bigger, then this number would have to be smaller. It would be cool if it were possible to work out what is the memory available on the GPU, then limit the size of the training dataset to this value.

**Comment by maweigert** [comment]
Hi,

I am not sure if I understand your problem: The number of training pairs is only really limited by your CPU RAM, not by GPU memory. The latter is only relevant for the training and can potentially be adjusted by changing the training config (e.g. by lowering the batchsize).
