### ISSUE TITLE
Question about Gaussian approximation of PSF

### ISSUE THREAD

**Issue by Luchixiang** [CSBDeep/CSBDeep#75]
Hi. Thanks for your awesome code and tutorial.
 I'm still not sure how to decide the standard deviation when using the Gaussian approximation for PSF.

1. Does the Std mean the Std value of the central YZ view of my 3D PSF stack? For an 3D stack, the std along an axis (for example, axis=0) should be a 2D image. How to extract a specific value?
2. In my generated PSF, the standard deviation is usually large for 16-bit stacks (e.g., 4500) while in the tutorial is small like 1, 3.

**Comment by zxy126** [comment]
+1,
I have same question about how to get the sigma for the picture even I read the paper about the IsoNet split.

Should I use light sheet imaging beads , and calculate the PSF by Huygens PSF Distiller or just measure anything.

**Comment by maweigert** [comment]
Hi,

sorry for the late answer. Please have a look at this issue that discusses the choice of the PSF for the isotropic reconstruction workflow: https://github.com/CSBDeep/CSBDeep/issues/10
