### ISSUE TITLE
Deprecated alias np.int

### ISSUE THREAD

**Issue by pawlowska** [CSBDeep/CSBDeep#76]
When trying to run 1_datagen notebook for retina example, I am encountering errors. One of them is in create_patches chunk:

`AtributeError: module 'numpy' has no attribute 'int'. 'np.int' was deprecated...` 

it appears that installing csbdeep (I have 0.7.4) with pip allows a newer version of Numpy (I have 1.26.4) that is not compatible with create_patches.

**Comment by uschmidt83** [comment]
Thanks for raising the issue and sorry for the late reply. This was fixed by #77 and will be part of the next release.
