### ISSUE TITLE
Stardist, changed backbone to UNET ASPP hybrid attention model But loading " ValueError: Layer count mismatch when loading weights from file. Model expected 25 layers, found 55 saved layers." 

### ISSUE THREAD

**Issue by Nal44** [CSBDeep/CSBDeep#82]
Hi,

I changed the unet backbone in stardist (3D) and transformed into a UNET, ASPP, with and hybrid attention mechanism (with Unet depth =4) .

The training is done and the threshold are being optimized,
But when I try to load the model into stardist Napari  I get the following : 

File C:\ProgramData\anaconda3\envs\starGPUv2_1\lib\site-packages\csbdeep\models\base_model.py:185, in BaseModel.load_weights(self=StarDist3D(stardist3danthogpatch481601603dall031..., 'patience': 40, 'min_delta': 0}, use_gpu=False), name='weights_best.h5')
    178 """Load neural network weights from model folder.
    179
    180 Parameters
   (...)
    183     Name of HDF5 weight file (as saved during or after training).
    184 """
--> 185 self.keras_model.load_weights(str(self.logdir/name))
        self.keras_model = <Functional name=functional, built=True>
        self = StarDist3D(stardist3danthogpatch481601603dall03122024batch2rays96asppattentionhybridFOVlargenamed): ZYXC → ZYXC
├─ Directory: 
└─ Config3D(n_dim=3, axes='ZYXC', n_channel_in=1, n_channel_out=97, train_checkpoint='weights_best.h5', train_checkpoint_last='weights_last.h5', train_checkpoint_epoch='weights_now.h5', n_rays=96, grid=(2, 4, 4), anisotropy=(1.7941176470588236, 1.0517241379310345, 1.0), backbone='unet', rays_json={'name': 'Rays_GoldenSpiral', 'kwargs': {'n': 96, 'anisotropy': (1.7941176470588236, 1.0517241379310345, 1.0)}}, n_classes=None, unet_n_depth=4, unet_kernel_size=[3, 3, 3], unet_n_filter_base=32, unet_n_conv_per_depth=2, unet_pool=[2, 2, 2], unet_activation='relu', unet_last_activation='relu', unet_batch_norm=False, unet_dropout=0.0, unet_prefix='', net_conv_after_unet=128, net_input_shape=[None, None, None, 1], net_mask_shape=[None, None, None, 1], train_patch_size=[32, 192, 192], train_background_reg=0.0001, train_foreground_only=0.9, train_sample_cache=True, train_dist_loss='mae', train_loss_weights=[1, 0.2], train_class_weights=[1, 1], train_epochs=400, train_steps_per_epoch=100, train_learning_rate=0.0003, train_batch_size=2, train_n_val_patches=None, train_tensorboard=True, train_reduce_lr={'factor': 0.5, 'patience': 40, 'min_delta': 0}, use_gpu=False)
        self.logdir = WindowsPath('
        name = 'weights_best.h5'

File ~\AppData\Roaming\Python\Python310\site-packages\keras\src\utils\traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args=(<Functional name=functional, built=True>, r'C:\Users\m197816\AppData\Local\Programs\Microsof...6asppattentionhybridFOVlargenamed\weights_best.h5'), **kwargs={})
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:

File ~\AppData\Roaming\Python\Python310\site-packages\keras\src\legacy\saving\legacy_h5_format.py:357, in load_weights_from_hdf5_group(f=<Closed HDF5 file>, model=<Functional name=functional, built=True>)
    356 if len(layer_names) != len(filtered_layers):
--> 357     raise ValueError(
        filtered_layers = [<Conv3D name=conv3d, built=True>, <Conv3D name=conv3d_1, built=True>, <Conv3D name=conv3d_2, built=True>, <Conv3D name=conv3d_3, built=True>, <Conv3D name=down_level_0_no_0, built=True>, <Conv3D name=down_level_0_no_1, built=True>, <Conv3D name=down_level_1_no_0, built=True>, <Conv3D name=down_level_1_no_1, built=True>, <Conv3D name=down_level_2_no_0, built=True>, <Conv3D name=down_level_2_no_1, built=True>, <Conv3D name=down_level_3_no_0, built=True>, <Conv3D name=down_level_3_no_1, built=True>, <Conv3D name=middle_0, built=True>, <Conv3D name=middle_2, built=True>, <Conv3D name=up_level_3_no_0, built=True>, <Conv3D name=up_level_3_no_2, built=True>, <Conv3D name=up_level_2_no_0, built=True>, <Conv3D name=up_level_2_no_2, built=True>, <Conv3D name=up_level_1_no_0, built=True>, <Conv3D name=up_level_1_no_2, built=True>, <Conv3D name=up_level_0_no_0, built=True>, <Conv3D name=up_level_0_no_2, built=True>, <Conv3D name=features, built=True>, <Conv3D name=prob, built=True>, <Conv3D name=dist, built=True>]
        len(filtered_layers) = 25
        layer_names = ['conv3d', 'conv3d_1', 'conv3d_2', 'conv3d_3', 'down_level_0_no_0', 'down_level_0_no_1', 'down_level_1_no_0', 'down_level_1_no_1', 'down_level_2_no_0', 'down_level_2_no_1', 'down_level_3_no_0', 'down_level_3_no_1', 'ASPP_GAP_conv', 'ASPP_1x1_conv', 'ASPP_3x3_conv_rate_6', 'ASPP_3x3_conv_rate_12', 'ASPP_3x3_conv_rate_18', 'Post_ASPP_conv', 'conv3d_4', 'conv3d_5', 'conv3d_6', 'conv3d_7', 'dense', 'dense_1', 'conv3d_8', 'up_level_3_no_0', 'up_level_3_no_1', 'conv3d_9', 'conv3d_10', 'conv3d_11', 'dense_2', 'dense_3', 'conv3d_12', 'up_level_2_no_0', 'up_level_2_no_1', 'conv3d_13', 'conv3d_14', 'conv3d_15', 'dense_4', 'dense_5', 'conv3d_16', 'up_level_1_no_0', 'up_level_1_no_1', 'conv3d_17', 'conv3d_18', 'conv3d_19', 'dense_6', 'dense_7', 'conv3d_20', 'up_level_0_no_0', 'up_level_0_no_1', 'final_conv', 'features', 'prob', 'dist']
        len(layer_names) = 55
    358         "Layer count mismatch when loading weights from file. "
    359         f"Model expected {len(filtered_layers)} layers, found "
    360         f"{len(layer_names)} saved layers."
    361     )
    363 for k, name in enumerate(layer_names):

ValueError: Layer count mismatch when loading weights from file. Model expected 25 layers, found 55 saved layers.

The above exception was the direct cause of the following exception:

EmitLoopError                             Traceback (most recent call last)
File _value_widget.py:65, in ValueWidget._on_value_change(self=PushButton(value=False, annotation=None, name='call_button'), value=False)
     63 if value is self.null_value and not self._nullable:
     64     return
---> 65 self.changed.emit(value)
        value = False
        self.changed = <SignalInstance 'changed' on PushButton(value=False, annotation=None, name='call_button')>
        self = PushButton(value=False, annotation=None, name='call_button')

File C:\ProgramData\anaconda3\envs\starGPUv2_1\lib\site-packages\psygnal\_signal.py:927, in SignalInstance.emit(self=<SignalInstance 'changed' on PushButton(value=False, annotation=None, name='call_button')>, check_nargs=False, check_types=False, asynchronous=False, *args=(False,))
    924     sd.start()
    925     return sd
--> 927 self._run_emit_loop(args)
        self = <SignalInstance 'changed' on PushButton(value=False, annotation=None, name='call_button')>
        args = (False,)
    928 return None

File C:\ProgramData\anaconda3\envs\starGPUv2_1\lib\site-packages\psygnal\_signal.py:974, in SignalInstance._run_emit_loop(self=<SignalInstance 'changed' on PushButton(value=False, annotation=None, name='call_button')>, args=(False,))
    972                 caller.cb(args)
    973             except Exception as e:
--> 974                 raise EmitLoopError(
        caller = <psygnal._weak_callback._StrongFunction object at 0x000001827E487C70>
        args = (False,)
    975                     slot_repr=repr(caller), args=args, exc=e
    976                 ) from e
    978 return None

EmitLoopError: calling <psygnal._weak_callback._StrongFunction object at 0x000001827E487C70> with args=(False,) caused ValueError: Layer count mismatch when loading weights from file. Model expected 25 layers, found 55 saved layers..

The model was trained from strach and the layers names are : 

from stardist.models import Config3D

# Assume config is None or loaded from some configuration file
config = Config3D()

# Get the model architecture (example)
def get_model_layers_from_config(config):
    model = StarDist3D(config=config)
    model_layers = [layer.name for layer in model.keras_model.layers]
    return model_layers

model_layers = get_model_layers_from_config(config)
print("Model layers:")
for i, layer_name in enumerate(model_layers):
    print(f"{i}: {layer_name}")

Using default values: prob_thresh=0.5, nms_thresh=0.4.
Model layers:
0: input
1: down_level_0_no_0
2: activation_21
3: down_level_0_no_1
4: activation_22
5: max_0
6: down_level_1_no_0
7: activation_23
8: down_level_1_no_1
9: activation_24
10: max_1
11: global_average_pooling3d_5
12: reshape_5
13: ASPP_GAP_conv
14: ASPP_1x1_conv
15: ASPP_3x3_conv_rate_6
16: ASPP_3x3_conv_rate_12
17: ASPP_3x3_conv_rate_18
18: lambda_1
19: ASPP_concat
20: Post_ASPP_conv
21: activation_25
22: upsample_1
23: conv3d_21
24: conv3d_22
25: conv3d_23
26: add_4
27: activation_26
28: conv3d_24
29: multiply_12
30: global_average_pooling3d_6
31: global_max_pooling3d_4
32: tf.concat_8
33: dense_8
34: dense_9
35: tf.math.reduce_mean_4
36: tf.math.reduce_max_4
37: reshape_6
38: tf.concat_9
39: multiply_13
40: conv3d_25
41: multiply_14
42: concat_1
43: up_level_1_no_0
44: activation_27
45: up_level_1_no_1
46: activation_28
47: upsample_0
48: conv3d_26
49: conv3d_27
50: add_5
51: activation_29
52: conv3d_28
53: multiply_15
54: global_average_pooling3d_7
55: global_max_pooling3d_5
56: tf.concat_10
57: dense_10
58: dense_11
59: tf.math.reduce_mean_5
60: tf.math.reduce_max_5
61: reshape_7
62: tf.concat_11
63: multiply_16
64: conv3d_29
65: multiply_17
66: concat_0
67: up_level_0_no_0
68: activation_30
69: up_level_0_no_1
70: activation_31
71: final_conv
72: final_activation
73: features
74: prob
75: dist

Any idea how to fix that ? 

Thanks !

PS  : I can share the Unet block modifications if interested (ASPP+Hybrid attention).

THanks,
antho

**Comment by maweigert** [comment]
Hi @Nal44 ,

this is very hard to debug with the information that you provided. 

Maybe its easier for you to debug by first trying to save a new model with your backbone, try to loading it and then see whether that error persists (i.e. without training and using napari)

**Comment by Nal44** [comment]
Hi Martin,

Inside the notebook training) the model loads and run fine, there are not issues...
The issues arise when using in stardist-napari...

This issue has been reported, and this might work :  model.load_weights('path_to_weights.h5', by_name=True).
But not sure how to change this in Napari stardist to modifiy how the model weights are loaded ?

perhaps modifying this file directly : C:\ProgramData\anaconda3\envs\starGPUv2_1\lib\site-packages\csbdeep\models\base_model.py ? 

Thanks a lot,
Antho

**Comment by Nal44** [comment]
Hi Martin,
Turns out the way I names the layers and wrote the model was wrong.
Now I can train and save the model then load and the weights problem is solved.

I can send the model (Unet hybrid attention FNP/ASPP) if interested (28millions parameters).
Thanks,
antho

**Comment by Nal44** [comment]
Hi, in fact the issue persist ...!

The new model load well and can predict in my jupyter notebook , but when I upload the model into Napari-stardist then I have the mismatch ...

I dont know how to fix this in napari-stardist , but it should be a way since it runs /predict in the Jupyter notebook ...

Here is the log from stardist-Napari : 

Loading network weights from 'weights_best.h5'.
Error loading model: Layer count mismatch when loading weights from file. Model expected 25 layers, found 46 saved layers. - stardist3d_alllayers_aspp_hybridattention_allshapes_graphbased
Traceback (most recent call last):
  File "file\last\src\napari_senoquant\NucleiWidget.py", line 606, in loadModel
    model: StarDistBase = StarDist3D(
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\stardist\models\model3d.py", line 348, in __init__
    super().__init__(config, name=name, basedir=basedir)
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\stardist\models\base.py", line 231, in __init__
    super().__init__(config=config, name=name, basedir=basedir)
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\csbdeep\models\base_model.py", line 162, in __init__
    self._find_and_load_weights()
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\csbdeep\models\base_model.py", line 33, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\csbdeep\models\base_model.py", line 217, in _find_and_load_weights
    self.load_weights(weights_chosen.name)
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\csbdeep\models\base_model.py", line 33, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\csbdeep\models\base_model.py", line 234, in load_weights
    self.keras_model.load_weights(str(self.logdir/name))
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\M197816\.conda\envs\napari_env\lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 357, in load_weights_from_hdf5_group
    raise ValueError(
ValueError: Layer count mismatch when loading weights from file. Model expected 25 layers, found 46 saved layers.


The only thing I change is the block.py to add the new blocks / layers and modified the Unet architecture ... 

Hence I don't know how to fix it and make it run into Napari-stardist ? 

I can share the model and the block.py that I modified, if this can help to resolve the problem.

Please let me know,
thanks a lot
antho

**Comment by Nal44** [comment]
Issue : 

File ~\.conda\envs\napari_env\lib\site-packages\csbdeep\models\base_model.py:234, in BaseModel.load_weights(self=StarDist3D(stardist3d_alllayers_aspp_hybridatten..., 'patience': 40, 'min_delta': 0}, use_gpu=False), name='weights_best.h5')
    225 @suppress_without_basedir(warn=True)
    226 def load_weights(self, name='weights_best.h5'):
    227     """Load neural network weights from model folder.
    228
    229     Parameters
   (...)
    232         Name of HDF5 weight file (as saved during or after training).
    233     """
--> 234     self.keras_model.load_weights(str(self.logdir/name))
        self.keras_model = <Functional name=functional_3, built=True>
        self = StarDist3D(stardist3d_alllayers_aspp_hybridattention_allshapes_graphbased): ZYXC → ZYXC
├─ Directory: C:\Users\M197816\AppData\Local\Programs\Microsoft VS Code\models\models\stardist3d_alllayers_aspp_hybridattention_allshapes_graphbased
└─ Config3D(n_dim=3, axes='ZYXC', n_channel_in=1, n_channel_out=97, train_checkpoint='weights_best.h5', train_checkpoint_last='weights_last.h5', train_checkpoint_epoch='weights_now.h5', n_rays=96, grid=(2, 4, 4), anisotropy=(1.7851851851851852, 1.0432900432900434, 1.0), backbone='unet', rays_json={'name': 'Rays_GoldenSpiral', 'kwargs': {'n': 96, 'anisotropy': (1.7851851851851852, 1.0432900432900434, 1.0)}}, n_classes=None, unet_n_depth=4, unet_kernel_size=[3, 3, 3], unet_n_filter_base=32, unet_n_conv_per_depth=2, unet_pool=[2, 2, 2], unet_activation='relu', unet_last_activation='relu', unet_batch_norm=False, unet_dropout=0.0, unet_prefix='', net_conv_after_unet=128, net_input_shape=[None, None, None, 1], net_mask_shape=[None, None, None, 1], train_patch_size=[32, 192, 192], train_background_reg=0.0001, train_foreground_only=0.9, train_sample_cache=True, train_dist_loss='mae', train_loss_weights=[1, 0.2], train_class_weights=[1, 1], train_epochs=400, train_steps_per_epoch=100, train_learning_rate=0.0003, train_batch_size=2, train_n_val_patches=None, train_tensorboard=True, train_reduce_lr={'factor': 0.5, 'patience': 40, 'min_delta': 0}, use_gpu=False)
        self.logdir = WindowsPath('C:/Users/M197816/AppData/Local/Programs/Microsoft VS Code/models/models/stardist3d_alllayers_aspp_hybridattention_allshapes_graphbased')
        name = 'weights_best.h5'

File ~\.conda\envs\napari_env\lib\site-packages\keras\src\utils\traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args=(<Functional name=functional_3, built=True>, r'C:\Users\M197816\AppData\Local\Programs\Microsof...ridattention_allshapes_graphbased\weights_best.h5'), **kwargs={})
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File ~\.conda\envs\napari_env\lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py:357, in load_weights_from_hdf5_group(f=<Closed HDF5 file>, model=<Functional name=functional_3, built=True>)
    355 layer_names = filtered_layer_names
    356 if len(layer_names) != len(filtered_layers):
--> 357     raise ValueError(
        filtered_layers = [<Conv3D name=conv3d_12, built=True>, <Conv3D name=conv3d_13, built=True>, <Conv3D name=conv3d_14, built=True>, <Conv3D name=conv3d_15, built=True>, <Conv3D name=down_level_0_no_0, built=True>, <Conv3D name=down_level_0_no_1, built=True>, <Conv3D name=down_level_1_no_0, built=True>, <Conv3D name=down_level_1_no_1, built=True>, <Conv3D name=down_level_2_no_0, built=True>, <Conv3D name=down_level_2_no_1, built=True>, <Conv3D name=down_level_3_no_0, built=True>, <Conv3D name=down_level_3_no_1, built=True>, <Conv3D name=middle_0, built=True>, <Conv3D name=middle_2, built=True>, <Conv3D name=up_level_3_no_0, built=True>, <Conv3D name=up_level_3_no_2, built=True>, <Conv3D name=up_level_2_no_0, built=True>, <Conv3D name=up_level_2_no_2, built=True>, <Conv3D name=up_level_1_no_0, built=True>, <Conv3D name=up_level_1_no_2, built=True>, <Conv3D name=up_level_0_no_0, built=True>, <Conv3D name=up_level_0_no_2, built=True>, <Conv3D name=features, built=True>, <Conv3D name=prob, built=True>, <Conv3D name=dist, built=True>]
        len(filtered_layers) = 25
        layer_names = ['conv3d', 'conv3d_1', 'conv3d_2', 'conv3d_3', 'down_level_0_no_0', 'down_level_0_no_1', 'down_level_1_no_0', 'down_level_1_no_1', 'down_level_2_no_0', 'down_level_2_no_1', 'down_level_3_no_0', 'down_level_3_no_1', 'conv3d_4', 'conv3d_5', 'conv3d_6', 'ASPP_GAP_conv', 'ASPP_1x1_conv', 'ASPP_3x3_conv_rate_6', 'ASPP_3x3_conv_rate_12', 'ASPP_3x3_conv_rate_18', 'hybrid_attention', 'Post_ASPP_conv', 'up_level_3_no_0', 'up_level_3_no_1', 'conv3d_7', 'conv3d_8', 'conv3d_9', 'hybrid_attention_1', 'up_level_2_no_0', 'up_level_2_no_1', 'conv3d_10', 'conv3d_11', 'conv3d_12', 'hybrid_attention_2', 'up_level_1_no_0', 'up_level_1_no_1', 'conv3d_13', 'conv3d_14', 'conv3d_15', 'hybrid_attention_3', 'up_level_0_no_0', 'up_level_0_no_1', 'final_conv', 'features', 'prob', 'dist']
        len(layer_names) = 46



It seems like all layers /blocks that I added are not built into the model ... any method to add them into the built ? 

Thanks
antho

**Comment by Nal44** [comment]
filtered_layers = [<Conv3D name=conv3d_12, built=True>, <Conv3D name=conv3d_13, built=True>, <Conv3D name=conv3d_14, built=True>, <Conv3D name=conv3d_15, built=True>, <Conv3D name=down_level_0_no_0, built=True>, <Conv3D name=down_level_0_no_1, built=True>, <Conv3D name=down_level_1_no_0, built=True>, <Conv3D name=down_level_1_no_1, built=True>, <Conv3D name=down_level_2_no_0, built=True>, <Conv3D name=down_level_2_no_1, built=True>, <Conv3D name=down_level_3_no_0, built=True>, <Conv3D name=down_level_3_no_1, built=True>, <Conv3D name=middle_0, built=True>, <Conv3D name=middle_2, built=True>, <Conv3D name=up_level_3_no_0, built=True>, <Conv3D name=up_level_3_no_2, built=True>, <Conv3D name=up_level_2_no_0, built=True>, <Conv3D name=up_level_2_no_2, built=True>, <Conv3D name=up_level_1_no_0, built=True>, <Conv3D name=up_level_1_no_2, built=True>, <Conv3D name=up_level_0_no_0, built=True>, <Conv3D name=up_level_0_no_2, built=True>, <Conv3D name=features, built=True>, <Conv3D name=prob, built=True>, <Conv3D name=dist, built=True>]
        len(filtered_layers) = 25
        layer_names = ['conv3d', 'conv3d_1', 'conv3d_2', 'conv3d_3', 'down_level_0_no_0', 'down_level_0_no_1', 'down_level_1_no_0', 'down_level_1_no_1', 'down_level_2_no_0', 'down_level_2_no_1', 'down_level_3_no_0', 'down_level_3_no_1', 'conv3d_4', 'conv3d_5', 'conv3d_6', 'ASPP_GAP_conv', 'ASPP_1x1_conv', 'ASPP_3x3_conv_rate_6', 'ASPP_3x3_conv_rate_12', 'ASPP_3x3_conv_rate_18', 'hybrid_attention', 'Post_ASPP_conv', 'up_level_3_no_0', 'up_level_3_no_1', 'conv3d_7', 'conv3d_8', 'conv3d_9', 'hybrid_attention_1', 'up_level_2_no_0', 'up_level_2_no_1', 'conv3d_10', 'conv3d_11', 'conv3d_12', 'hybrid_attention_2', 'up_level_1_no_0', 'up_level_1_no_1', 'conv3d_13', 'conv3d_14', 'conv3d_15', 'hybrid_attention_3', 'up_level_0_no_0', 'up_level_0_no_1', 'final_conv', 'features', 'prob', 'dist']
        len(layer_names) = 46

**Comment by Nal44** [comment]
any help / feedback welcome :D 
thanks
antho
