### ISSUE TITLE
Joint Denoising and Projection Model

### ISSUE THREAD

**Issue by kapoorlab** [CSBDeep/CSBDeep#9]
Hi,

In the paper of CARE there is a model to perform joint complex task to perform projection and denoise the projection, but I can not find the model or associated notebook for this task. What happened to the projection + denoising workflow of CARE?

**Comment by uschmidt83** [comment]
Hi, as mentioned in [the documentation](http://csbdeep.bioimagecomputing.com/doc/), several features are still missing in the software. We will eventually add them, though. Thank you for your patience.

**Comment by kapoorlab** [comment]
Ah, thanks, I thought I was missing something.
